location:
  city: "Hyderabad"
  country: "India"
  method: 1

runtime:
  timezone: "Asia/Kolkata"
  check_interval_seconds: 20
  trigger_window_seconds: 90

behavior:
  prayers: ["Fajr", "Dhuhr", "Asr", "Maghrib", "Isha"]

audio:
  mode: "system"   # console | system
  files:
    fajr: assets/audio/azan_fajr.wav
    default: assets/audio/azan.wav

ramadan_override:
  enabled: true    # Use local masjid timetable for Fajr & Maghrib during Ramadan
